<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  margin: 0;
 background-color:black;
}

.bg {
  /* The image used */
  background-image: url("<?php echo base_url(); ?>media/images/cinema.jpg");

  /* Full height */
  height: 100%; 

  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: 100% 100%;
 
}

.video-size {
    position: absolute;
	width:63%;
	height:auto;
	margin-top:0%;
	margin-left:19%;
	
}
.slide-in-fwd-center {
	-webkit-animation: slide-in-fwd-center 3s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-fwd-center 3s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2019-5-31 17:4:57
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-fwd-center
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-fwd-center {
  0% {
    -webkit-transform: translateZ(-1400px);
            transform: translateZ(-1400px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes slide-in-fwd-center {
  0% {
    -webkit-transform: translateZ(-1400px);
            transform: translateZ(-1400px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}


</style>
</head>
<body>

<div class="bg">

<video   class="video-size slide-in-fwd-center" onended="window.location.href = '<?php echo site_url($controller.'/pitanje/'.$broj) ?>';"   autoplay  >
  <source src="<?php echo base_url(); ?>media/videos/<?php if(isset($scena))echo $scena; ?>.mp4" type="video/mp4">
  <source src="<?php echo base_url(); ?>media/videos/<?php if(isset($scena))echo $scena; ?>.ogg" type="video/ogg">
 </video>


 </div>



    <script>
        if(performance.navigation.type !==0){
       window.location.href="<?php $stranica = site_url($controller.'/redirectPage');  echo $stranica;?>"; 
    } 
    </script>

</body>
</html>