<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>mystyle.css">
<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>user.css">
<style>
.col{
    margin-top: 20%;
    transform: translateY(-50%);
    text-align: center;
   color:#FFDF00;
}
.slide-in-fwd-center {
	-webkit-animation: slide-in-fwd-center 0.98s cubic-bezier(0.250, 0.460, 0.450, 0.940) infinite both;
	        animation: slide-in-fwd-center 0.98s cubic-bezier(0.250, 0.460, 0.450, 0.940) infinite both;
}/* ----------------------------------------------
 * Generated by Animista on 2019-5-31 19:24:1
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-fwd-center
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-fwd-center {
  0% {
    -webkit-transform: translateZ(-1400px);
            transform: translateZ(-1400px);
    opacity: 0;font-size: 10px;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;font-size: 200px;
  }
}
@keyframes slide-in-fwd-center {
  0% {
    -webkit-transform: translateZ(-1400px);
            transform: translateZ(-1400px);
    opacity: 0;font-size: 10px;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;font-size: 200px;
  }
}



</style>
</head>
<body>
<div class = "container" >
<div class = "row" >
<div class = "col">
    <div id="txt" class="slide-in-fwd-center">Ready</div>	 

</div>	
</div>	
</div>	
<script>
var timeleft = 3;
var downloadTimer = setInterval(function(){
timeleft -= 1;      
if(timeleft == 2) {document.getElementById("txt").innerHTML="Set";}
  if(timeleft <= 1){
    window.location.href = "<?php echo site_url($controller.'/screen321') ?>";
  }

}, 1000);

    if(performance.navigation.type !==0){
       window.location.href="<?php $stranica = site_url($controller.'/redirectPage');  echo $stranica;?>"; 
    } 

</script>
</body>
</html>
